language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm

before_script:
  - composer install --prefer-source --dev

script:
  - php vendor/bin/phpunit -v --coverage-clover ./build/coverage/clover.xml

after_script:
  - php vendor/bin/coveralls -v
